# Generated by Django 5.0.7 on 2024-08-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_person_date_of_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
