# Generated by Django 5.0.7 on 2024-08-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_person_nationality_person_parent_or_guardian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
