# Generated by Django 5.0.7 on 2024-08-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_taxpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
