# Generated by Django 5.0.7 on 2024-08-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
