# Generated by Django 5.0.7 on 2024-08-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_person_first_name_person_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='social_security_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
