# Generated by Django 5.0.7 on 2024-08-26 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_person_phone_person_social_security_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('registration_fee_paid', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.member')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.month')),
            ],
        ),
    ]
